// Generate initial migration by inspecting known tables
import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';

config({ path: '.dev.vars' });

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

// Known tables from your application
const TABLES = [
  'profiles',
  'identity_graph',
  'events',
  'posts',
  'tags',
  'post_tags',
  'comments'
];

async function inspectTable(tableName) {
  const { data, error } = await supabase
    .from(tableName)
    .select('*')
    .limit(1);

  if (error) {
    console.log(`⚠️  ${tableName}: ${error.message}`);
    return null;
  }

  if (!data || data.length === 0) {
    console.log(`📭 ${tableName}: empty`);
    return { tableName, columns: [] };
  }

  const sample = data[0];
  const columns = Object.entries(sample).map(([name, value]) => ({
    name,
    type: typeof value,
    sample: value
  }));

  console.log(`✅ ${tableName}: ${columns.length} columns`);
  return { tableName, columns, sample };
}

async function generateSchema() {
  console.log('🔍 Inspecting database tables...\n');

  const results = [];
  for (const table of TABLES) {
    const result = await inspectTable(table);
    if (result) results.push(result);
  }

  let migration = `-- Initial Schema Migration
-- Generated: ${new Date().toISOString()}
-- 
-- This migration represents the current production database state.
-- It was generated by inspecting live tables and inferring types.
-- 
-- ⚠️  IMPORTANT: This is a best-effort schema. Review and adjust as needed.
-- For the authoritative schema, export directly from Supabase Dashboard.

`;

  results.forEach(({ tableName, columns, sample }) => {
    migration += `\n-- ============================================================================
-- Table: ${tableName}
-- ============================================================================\n`;
    
    if (sample) {
      migration += `/*\nSample row:\n${JSON.stringify(sample, null, 2)}\n*/\n\n`;
    }

    migration += `CREATE TABLE IF NOT EXISTS ${tableName} (\n`;
    
    const columnDefs = columns.map(({ name, type, sample }) => {
      let pgType = 'TEXT';
      
      // Infer PostgreSQL types
      if (name === 'id' || name.endsWith('_id')) pgType = 'UUID';
      else if (type === 'number') pgType = 'INTEGER';
      else if (type === 'boolean') pgType = 'BOOLEAN';
      else if (name.includes('timestamp') || name.includes('_at')) pgType = 'TIMESTAMPTZ';
      else if (Array.isArray(sample)) pgType = 'TEXT[]';
      else if (typeof sample === 'object' && sample !== null) pgType = 'JSONB';
      
      return `  ${name} ${pgType}`;
    });

    migration += columnDefs.join(',\n');
    migration += `\n);\n`;
  });

  migration += `\n\n-- ============================================================================
-- NOTES
-- ============================================================================
/*
 * This schema was auto-generated by inspecting live data.
 * You should:
 * 
 * 1. Add PRIMARY KEY constraints
 * 2. Add FOREIGN KEY constraints  
 * 3. Add UNIQUE constraints
 * 4. Add DEFAULT values
 * 5. Add NOT NULL constraints
 * 6. Add indexes
 * 7. Add views and functions
 * 
 * To get the complete schema with all constraints:
 * Go to Supabase Dashboard → SQL Editor → Run:
 * 
 * SELECT table_name, column_name, data_type, is_nullable, column_default
 * FROM information_schema.columns
 * WHERE table_schema = 'public'
 * ORDER BY table_name, ordinal_position;
 */
`;

  fs.writeFileSync('migrations/001_initial_schema_draft.sql', migration);
  console.log('\n✅ Generated migrations/001_initial_schema_draft.sql');
  console.log('\n💡 Next steps:');
  console.log('   1. Review the generated file');
  console.log('   2. Export full schema from Supabase Dashboard');
  console.log('   3. Merge the two to create final 001_initial_schema.sql');
}

generateSchema();
